### ISSUE TITLE
Jaeger in Springboot 2.0.0+ 

### ISSUE THREAD

**Issue by siddharthsethi11** [pavolloffay/opentracing-spring-boot-istio#1]
Hi what needs to be done to implement jaeger tracing in spring 2.0.0 and higher. I tried using this implementation but didn't work for me. 

Thanks 
Siddharth

**Comment by pavolloffay** [comment]
Hi you can use version 0.2.x which is compatible with SB 2.x. https://github.com/opentracing-contrib/java-spring-cloud#opentracing-spring-cloud

Feel free to reopen if there are still any problems
